TA_Typing1/Controllers/HomeController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TA_Typing1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;

namespace TA_Typing1.Controllers
{
    public class HomeController : Controller
    {
        private MyDbContext db;
        private UserManager<ApplicationUser> manager;
        
        public HomeController()
        {
            db = new MyDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

        public ActionResult Index(string optPrg = "1_pb", string skp_ad = "off")
        {
            ViewBag.optPrg = optPrg;    // the option of the program
            ViewBag.skp_ad = skp_ad;    // skip the advertisement
            ApplicationUser adminID = db.Users.Where(user => user.UserName =="admin").First();

            if (User.Identity.IsAuthenticated)
            {
                var currentUser = manager.FindById(User.Identity.GetUserId());

                // to check if the words database is empty
                int count = 0;
                IEnumerable<Word> wordAmount = db.Words.ToList().Where(word => word.User.Id == currentUser.Id);
                foreach (var item in wordAmount)
                {
                    count++;
                }
                ViewBag.count = count;
            }
                
            switch (optPrg)
            {
                case "1_pb":
                    ViewBag.wordList = db.Words.ToList().Where(word => word.User.Id == adminID.Id && word.WordDetail.Level == 1);                    
                    return View();
                case "2_pb":
                    ViewBag.wordList = db.Words.ToList().Where(word => word.User.Id == adminID.Id && (word.WordDetail.Level == 1 || word.WordDetail.Level == 2));
                    return View();
                case "3_pb":
                    ViewBag.wordList = db.Words.ToList().Where(word => word.User.Id == adminID.Id && (word.WordDetail.Level == 1 || word.WordDetail.Level == 2 || word.WordDetail.Level == 3));
                    return View();
                case "1_pr":
                    if (User.Identity.IsAuthenticated)
                    {
                        var currentUser = manager.FindById(User.Identity.GetUserId());
                        ViewBag.wordList = db.Words.ToList().Where(word => word.User.Id == currentUser.Id);
                        return View();
                    }
                    else
                        return View();
                default:
                    return View();
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TA_Typing1/Controllers/RecordsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TA_Typing1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace TA_Typing1.Controllers
{
    public class RecordsController : Controller
    {
        private MyDbContext db;
        private UserManager<ApplicationUser> manager;
        public RecordsController()
        {
            db = new MyDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

        // GET: Records
        public ActionResult publicRecords()
        {
            return View(db.Records.ToList().Where(record => record.pri_rec == false).OrderByDescending(record => record.wpm));
        }
        [Authorize]
        public async Task<ActionResult> privateRecords()
        {
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            return View(db.Records.ToList().Where(record => record.User.Id == currentUser.Id).OrderByDescending(record => record.CreatedTime));
        }
        // POST: Records/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "wpm, pri_rec")] Record record)
        {
            
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());

                if (ModelState.IsValid)
                {
                    record.CreatedTime = DateTime.Now.ToUniversalTime();
                    record.User = currentUser;

                    db.Records.Add(record);
                    db.SaveChanges();

                    return RedirectToAction("publicRecords");
                }

            return View();
        }

        // GET: Records/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TA_Typing1/Controllers/WordsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using TA_Typing1.Models;
using TA_Typing1.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;

namespace TA_Typing1.Controllers
{
    [Authorize]
    public class WordsController : Controller
    {
        static string fColor = "flash-default";
        private MyDbContext db;
        private UserManager<ApplicationUser> manager;
        public WordsController()
        {
            db = new MyDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
        }

        // GET: Words
        public ActionResult Index(string s_word = null, string s_date = "")
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            IEnumerable<Word> Words;
            if (s_word != null)
            {
                Words = db.Words.ToList().Where(w => w.WordDetail.WContext.ToLower().Contains(s_word.ToLower()) && w.User == currentUser);
                return View(Words);
            }
            else if (s_date != "")
            {
                string[] formats = {"MM/dd/yyyy", "MM-dd-yyyy"};
                DateTime date_query_real;
                if (!DateTime.TryParseExact(s_date, formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out date_query_real))
                {
                    throw new KeyNotFoundException(); //no thing at all
                }

                date_query_real = Convert.ToDateTime(s_date);

                Words = db.Words.ToList().Where(w => w.CreatedTime.Date == date_query_real && w.User == currentUser);
                return View(Words);
            }

            return View(db.Words.ToList().Where(word => word.User == currentUser));
        }

        // GET: Words/Details/5
        public ActionResult Details(int? id)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Word word = db.Words.Find(id);

            if (word == null)
            {
                return HttpNotFound();
            }
            else if (word.User != currentUser)
            {
                // not authorized
                return HttpNotFound();
            }

            IEnumerable<Word> nextWords = db.Words.ToList().Where(w => w.Id > word.Id && w.User.Id == currentUser.Id).OrderByDescending(w => w.Id);
            IEnumerable<Word> prevWords = db.Words.ToList().Where(w => w.Id > 0 && w.Id < word.Id && w.User.Id == currentUser.Id).OrderByDescending(w => w.Id);
            if (nextWords.Count() == 0)
            {
                @ViewBag.nextWord = null;
            }
            else
            {
                @ViewBag.nextWord = nextWords.Last().Id;
            }

            if (prevWords.Count() == 0)
            {
                @ViewBag.prevWord = null;
            }
            else
            {
                @ViewBag.prevWord = prevWords.First().Id;
            }
            // The list of word defs are added
            word.WordDefs = db.WordDefs.ToList().Where(worddef => worddef.wordId == word.Id);

            return View(word);
        }

        // GET: Words/Create
        public ActionResult CreateSingle()
        {
            return View();
        }

        // POST: Words/CreateSingle
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSingle(Word word)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                word.WordDetail.WContext = word.WordDetail.WContext.Trim();
                word.WordDetail.Level = 1; // phrase
                word.User = currentUser;
                word.CreatedTime = DateTime.UtcNow;
                word.WordDetail.CreatedTime = DateTime.UtcNow;
                db.Words.Add(word);
                db.WordDetail.Add(word.WordDetail);
                db.SaveChanges();
                ViewBag.redirectUrl = Url.Action("details", "words", new { id = word.Id });
                new FlashCardsController().CreateFlashCard(word, fColor);

                return PartialView("_RedirectPage");
            }

            return View();
        }

        // GET: Words/CreateMultiple
        public ActionResult CreateMultiple()
        {
            return View();
        }

        // POST: Words/CreateMultiple
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMultiple(Word words)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if (ModelState.IsValid)
            {
                ViewBag.redirectUrl = Url.Action("index");
                char[] delimiterChars = { ',', '\t', '\n' };
                string[] word = words.WordDetail.WContext.Split(delimiterChars);

                Word ipWord = words;
                ipWord.WordDetail.Level = words.WordDetail.Level;
                ipWord.User = currentUser;

                for (int i = 0; i < word.Length; ++i)
                {
                    word[i] = word[i].Trim();

                    if (word[i] == "")
                        continue;

                    ipWord.WordDetail.WContext = word[i];
                    ipWord.CreatedTime = DateTime.UtcNow;
                    ipWord.WordDetail.WType = 1; // word
                    ipWord.WordDetail.CreatedTime = ipWord.CreatedTime;
                    db.Words.Add(ipWord);
                    db.WordDetail.Add(ipWord.WordDetail);
                    db.SaveChanges();
                    new FlashCardsController().CreateFlashCard(ipWord, fColor);
                }

                return PartialView("_RedirectPage");
            }

            return View();
        }

        // GET: Words/CreatePhrase
        public ActionResult CreatePhrase()
        {
            return View();
        }

        // POST: Words/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePhrase(Word word)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());
            if (ModelState.IsValid)
            {
                word.User = currentUser;
                word.CreatedTime = DateTime.UtcNow;
                word.WordDetail.CreatedTime = word.CreatedTime;
                word.WordDetail.WType = 2;
                db.Words.Add(word);
                db.WordDetail.Add(word.WordDetail);
                db.SaveChanges();
                ViewBag.redirectUrl = Url.Action("details", "words", new { id = word.Id });
                new FlashCardsController().CreateFlashCard(word, fColor);

                return PartialView("_RedirectPage");
            }

            return View();
        }

        // GET: Words/Edit/5
        public ActionResult Edit(int? id)
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Word word = db.Words.Find(id);
            if (word == null)
            {
                return HttpNotFound();
            }
            else if (word.User != currentUser)
            {
                // not authorized
                return HttpNotFound();
            }

            return View(word);
        }

        // POST: Words/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Word word)
        {
            if (ModelState.IsValid)
            {
                WordDetail wDetail = db.WordDetail.First(wd => wd.Id == word.WordDetail.Id);
                wDetail.CreatedTime = DateTime.Today;
                wDetail.WContext = word.WordDetail.WContext;
                wDetail.WPronounce = word.WordDetail.WPronounce;
                word.WordDetail = wDetail;
                //word.CreatedTime = word.CreatedTime.AddDays(-1);

                db.Entry(word).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.redirectUrl = Url.Action("details", "words", new { id = word.Id });
                return PartialView("_RedirectPage");
            }

            return View(word);
        }

        // POST: Words/Find
        public ActionResult Find(string s_word = "")
        {
            var currentUser = manager.FindById(User.Identity.GetUserId());

            IEnumerable<Word> wordsFound = db.Words.ToList().Where(w => w.WordDetail.WContext.ToLower().Contains(s_word.ToLower()) && w.User == currentUser);
            if (wordsFound.Count() == 1)
            {
                return RedirectToAction("details", "words", new { id = wordsFound.First().Id });
            }
            else
                return RedirectToAction("index", "words", new { s_word = s_word });
        }

        // GET: Words/Delete/5
        public ActionResult Delete(int? id)
        {

TA_Typing1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TA_Typing1/Views/Home/Index.cshtml
@model IEnumerable<TA_Typing1.Models.Word>

@{
    ViewBag.Title = "Home Page";
}
<div class="container" id="advertisement">
    <div class="text-center" style="margin-top:30px;">
        <button type="button" id="skip_fly" class="btn btn-default">skip <span class="glyphicon glyphicon-triangle-right"></span></button>
    </div>
    <div id="logo_fly" class="text-center" style="margin-bottom:60px; margin-top:10px;">
        <span class="glyphicon glyphicon-education hidden-xs" style="font-size:200px;"></span>
        <span class="glyphicon glyphicon-education visible-xs" style="font-size:100px;"></span>
    </div>
    <div id="title_fly" class="text-center" style="margin-bottom:60px; line-height:1.5;">
        <div id="type_fly" class="col-md-2 col-md-offset-3">
            <span class="hidden-sm hidden-xs" style="font-size:50px;">TYPE</span>
            <span class="visible-sm visible-xs" style="font-size:40px;">TYPE</span>
        </div>
        <div id="your_fly" class="col-md-2">
            <span class="hidden-sm hidden-xs" style="font-size:50px;">YOUR</span>
            <span class="visible-sm visible-xs" style="font-size:40px;">YOUR</span>
        </div>
        <div id="words_fly" class="col-md-3">
            <span class="hidden-sm hidden-xs" style="font-size:50px;">WORDS</span>
            <span class="visible-sm visible-xs" style="font-size:40px;">WORDS</span>
        </div>
    </div>
</div>
<div class="container" id="main_content" hidden="hidden">
    <!--Logo-->
    <div class="container" style="padding-top:20px;">
        <div class="col-md-3"></div>
        <div class="col-md-6 center-block text-center hidden-xs">
            <img src="~/Images/Logo/logo6_lg.png" style="height:80px;" />
        </div>
        <div class="col-md-3"></div>
    </div>
    <hr class="hidden-xs" />
    <!-- Main tabs-->
    <div class="container" style="background: linear-gradient(to bottom, #fff 60%, #f2f2f2 80%);">
        <div class="row">
            <!-- OPTION -->
            <div class="col-sm-3 text-center center-block">
                <h3>Use your words?</h3>
                <br />
                <!--
                    Modal button
                -->
                <div class="btn btn-primary refresh-btn" data-toggle="modal" data-target="#optionPrg" id="opt-btn">
                    <span style="margin-bottom:0px; padding-top:0px; font-size:16px;">Try now <span class="glyphicon glyphicon-step-forward"></span></span>
                </div>
                <br />
                <!-- Modal -->
                <div class="modal fade" id="optionPrg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Program Option</h4>
                            </div>
                            <div class="modal-body text-justify">
                                <form method="get" id="optForm">
                                    <!-- input skip advertisement option -->
                                    <input name="skp_ad" value="on" hidden />

                                    <h4><span class="text-info">Default Words</span></h4>
                                    <div>
                                        <h6><input type="radio" name="optPrg" value="1_pb" class="sbmOpt" /> Top 200 common words</h6>
                                    </div>
                                    <div>
                                        <h6><input type="radio" name="optPrg" value="2_pb" class="sbmOpt" /> Top 500 common words</h6>
                                    </div>
                                    <div>
                                        <h6><input type="radio" name="optPrg" value="3_pb" class="sbmOpt" /> Top 1000 common words</h6>
                                    </div>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <br />
                                        <h4><span class="text-info">My Words</span></h4>
                                        {
                                            if (ViewBag.count == 0)
                                            {
                                                <h6>
                                                    <span>
                                                        Your words list is empty, to add new words
                                                    </span><br />
                                                    <a href="@Url.Action("Index", "Words")"><span> click here</span></a>
                                                </h6>
                                            }
                                            else if (ViewBag.count < 5)
                                            {
                                                <h6>
                                                    <span style="line-height:1.5;">
                                                        You currently have @ViewBag.count words. At least 5 words have to be added to enable this option. To add more words
                                                    </span><br />
                                                    <a href="@Url.Action("Index", "Words")"><span class="btn btn-primary"> click here</span></a>
                                                </h6>
                                            }
                                            else
                                            {
                                                <h6>
                                                    <span>
                                                        <input type="radio" name="optPrg" value="1_pr" class="sbmOpt" /> Use my own words
                                                    </span>
                                                </h6>
                                            }
                                        }

                                    }

                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
            </div>

            <!-- COUNT TIME -->
            <div class="col-sm-3 col-sm-push-6 center-block text-center">
                <h3 class="hidden-xs">Remaining seconds</h3>
                <br />
                <span class="btn btn-default btn-lg disabled" style="padding-top: 10px;">
                    <span class="text-danger" style="font-size:40px" id="mins">00 :</span>
                    <span class="text-danger" style="font-size:40px" id="seconds"></span>
                </span>
                <br /><br />
            </div>

            <!-- GIVEN BOX -->
            <div class="col-sm-6 col-sm-pull-3 center-block text-center">
                <div id="given" class="form-inline table-bordered"></div>
                <div class="text-center text-success" style="margin-top:20px; margin-bottom:20px;">
                    <b id="greetings">
                    </b>
                </div>
                <br />
                <div class="text-center center-block">
                    <input type=text id="typed" name="typed" size=50 class="form-inline img-rounded table-bordered" autocomplete="off" autofocus />
                    <br /><br />
                    <button type="button" class="btn btn-danger" aria-label="Left Align" onclick="window.location = '@Url.Action("index", "home", new { skp_ad = "on" })';" id="refresh-btn">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                        Restart
                    </button>
                </div>
                <br />
            </div>

        </div>

    </div>
    <br />
    <div class="container" style="background: linear-gradient(to bottom, #fff 60%, #f2f2f2 80%);">
        @if (User.Identity.IsAuthenticated)
        {
            <div class="col-md-4 col-md-offset-1" id="publicRecord">
            </div>
            <div class="col-md-4 col-md-offset-2" id="privateRecord">
            </div>
        }
        else
        {
            <div class="col-md-3">

            </div>
            <div class="col-md-6" id="publicRecord">

            </div>
            <div class="col-md-3">

            </div>
        }

    </div>
    @using (Html.BeginForm("create", "records", FormMethod.Post, new { id = "resultSbm", hidden = "hidden" }))
    {
        @Html.AntiForgeryToken();
                                if (ViewBag.optPrg == "1_pr")
                                {
                                    <input type="text" name="pri_rec" value="true" id="pri_rec" />
                                }
                                else
                                {
                                    <input type="text" name="pri_rec" value="false" id="pri_rec" />
                                }

                                <input type="text" name="wpm" id="wpm" />
        
                                <input type="submit" />
    }
</div>
@section script{
    <script>

        msg = new Array(@{
        string sqWords = "";
        var count = 0;

        foreach (var item in ViewBag.wordList)
        {
            count++;
            sqWords += '"' + item.WordDetail.WContext + '"' + ',';
            }

        if (sqWords.Trim().Length > 0)
        {
            sqWords = sqWords.Remove(sqWords.Trim().Length - 1);
        }

        @Html.Raw((count<2)?"":sqWords);
    });

    </script>
    @if (count >= 5)
    {
        <script src="~/Scripts/_typingTest.js" type="text/javascript"></script>
    }

}

@section script2 {
    <script>

    function stopPrg() {
        stop = true;
        $("#given").fadeOut("normal", function () {
            $(this).empty();
        });

        $("#given").fadeIn("normal", function () {
            $(this).append("<center><h1><span><span class='glyphicon glyphicon-thumbs-up'></span> Congratulation</span></h1><br><h2 class=\"text-info\">" + correctWords + "(wpm)</h2><br><h3><table class='table'><tr><td>Total of words</td><td>" + totalWords + "</td></tr><tr><td>Total of characters</td><td> " + numChar + "</td></tr></table></h3></center>");
        });

        $('#result1').val(correctWords);
        $('#result2').val(totalWords);
        $('#result3').val(numChar);

        // add 07032015
        $('#wpm').val(correctWords);

        @if(User.Identity.IsAuthenticated)
    {
        @Html.Raw("$('#resultSbm').submit();");
    }
    }

    $(".sbmOpt").click(function () {
        $("#optForm").submit();
    })

    $(document).ready(function () {
        $("input[value='@ViewBag.optPrg']").prop('checked', true);

            $('#typed').keyup(function (evt) {
                if (evt.which === 32 && stop == true) {
                    // set empty
                    $('#typed').val("");
                }
            })
        })

        // upload file
        $(function () {

            $("#publicRecord").load("@Url.Action("publicRecords", "Records")");
            $("#privateRecord").load("@Url.Action("privateRecords", "Records")");

            $("#resultSbm").on("submit", function (e) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "/Records/Create",
                    data: $('#resultSbm').serialize(),
                    datatype: "html",
                    success: function (data) {
                        $('#publicRecord').html(data);
                        $("#privateRecord").load("Records/privateRecords");
                    }
                });
            })

        })
    </script>
}


@section flash_adv {
    <script>
        $(document).ready(function () {
            if ("@ViewBag.skp_ad" === "off") {
                $('#logo_fly').fadeOut(0);
                $('#type_fly').fadeOut(0);
                $('#your_fly').fadeOut(0);
                $('#words_fly').fadeOut(0);

                $('#logo_fly').slideDown(2000);
                $('#type_fly').delay(1000).slideUp(1000).fadeIn(2000);
                $('#your_fly').delay(2000).slideUp(1000).fadeIn(2000);
                $('#words_fly').delay(3000).slideUp(1000).fadeIn(2000);

                $('#advertisement').delay(6000).slideUp(600).fadeOut(200);
                $('#main_content').delay(7000).fadeIn(1000);

                $('#skip_fly').click(function () {
                    $('#logo_fly').clearQueue();
                    $('#type_fly').clearQueue();
                    $('#your_fly').clearQueue();
                    $('#words_fly').clearQueue();

                    $('#advertisement').hide();
                    $('#main_content').removeAttr("hidden");
                    //$('#main_content').slideDown(600).fadeIn(200);
                })
            }
            else {
                $('#advertisement').hide();
                $('#main_content').removeAttr("hidden");
            }

        })
    </script>
}